Indentation

diff --git a/tubestatus b/tubestatus
--- a/tubestatus
+++ b/tubestatus
@@ -28,8 +28,9 @@
 set -e
 
 if ! command -v jq &>/dev/null; then
-    printf "Error: You need to install jq to run this script\nhttps://stedolan.github.io/jq/download/\n"
-    exit 1
+  printf "Error: You need to install jq to run this script
+https://stedolan.github.io/jq/download/\n"
+  exit 1
 fi
 
 LINE_SEARCH=$1
@@ -41,13 +42,13 @@ NONE="\033[0m"
 URL="https://api.tfl.gov.uk/line/mode/tube,overground,dlr,tflrail/status"
 
 curl -s $URL |
-    jq --arg delim $DELIMITER -j '.[] |
+  jq --arg delim $DELIMITER -j '.[] |
       (.name) + $delim,
       (.lineStatuses[0] | (.statusSeverity),
       $delim + (.statusSeverityDescription),
       $delim + (.reason) + "\n")' |
-    awk -F $DELIMITER -v delim=$DELIMITER -v r=$RED \
-        -v y=$YELLOW -v g=$GREEN -v n=$NONE -v line=$LINE_SEARCH '{
+  awk -F $DELIMITER -v delim=$DELIMITER -v r=$RED \
+    -v y=$YELLOW -v g=$GREEN -v n=$NONE -v line=$LINE_SEARCH '{
               if ( $4 ) reason=$4;
               else reason="";
               if ( $2 == 10 ) color=g;
