Lint code

diff --git a/tubestatus b/tubestatus
--- a/tubestatus
+++ b/tubestatus
@@ -8,35 +8,9 @@
 #
 
 if ! command -v jq &>/dev/null; then
-  echo "You need to install jq to run this script."
-  echo "https://github.com/stedolan/jq"
-  echo
-  case "$OSTYPE" in
-  solaris*)
-    echo "pkgutil -i jq"
-    ;;
-  darwin*)
-    echo "brew install jq"
-    ;;
-  linux*)
-    echo "Debian/Ubuntu  sudo apt-get install jq"
-    echo "Fedora         sudo dnf install jq"
-    echo "openSUSE       sudo zipper install jq"
-    echo "Arch           sudo pacman -Sy jq"
-    ;;
-  bsd*)
-    echo "pkg install jq"
-    ;;
-  msys*)
-    echo "chocolatey install jq"
-    ;;
-  *)
-    echo "https://stedolan.github.io/jq/download/"
-    ;;
-  esac
-  exit 0
+    printf "Error: You need to install jq to run this script\nhttps://stedolan.github.io/jq/download/\n"
+    exit 1
 fi
-
 
 LINE_SEARCH=$1
 DELIMITER="¬"
@@ -47,13 +21,13 @@ NONE="\033[0m"
 URL="https://api.tfl.gov.uk/line/mode/tube,overground,dlr,tflrail/status"
 
 curl -s $URL |
-  jq --arg delim $DELIMITER -j '.[] |
+    jq --arg delim $DELIMITER -j '.[] |
       (.name) + $delim,
       (.lineStatuses[0] | (.statusSeverity),
       $delim + (.statusSeverityDescription),
       $delim + (.reason) + "\n")' |
-          awk -F $DELIMITER -v delim=$DELIMITER -v r=$RED \
-            -v y=$YELLOW -v g=$GREEN -v n=$NONE -v line=$LINE_SEARCH '{
+    awk -F $DELIMITER -v delim=$DELIMITER -v r=$RED \
+        -v y=$YELLOW -v g=$GREEN -v n=$NONE -v line=$LINE_SEARCH '{
               if ( $4 ) reason=$4;
               else reason="";
               if ( $2 == 10 ) color=g;
